CREATE TABLE registro (
  ID_PACIENTE varchar(10) PRIMARY KEY NOT NULL,
  DNI varchar(11),
  NOMBRES varchar(400),
  GENERO varchar(50),
  CELULAR int(15),
  DIRECCION TEXT,
  LOCACION TEXT,
  EDAD int(3),
  SEDE varchar(50),
  ESTADO varchar(50),
  TIME_AMP varchar(100),
  CANAL varchar(100),
  MOTIVO varchar(500),
  OBSERVACION TEXT,
  FECHA date DEFAULT CURDATE(),
  CORREO varchar(300),
  FECHANAC date,
  AFECCIONES varchar(500),
  ALERGIAS varchar(200),
  PDF longblob 
)

DELIMITER $$
CREATE TRIGGER tr_generar BEFORE INSERT ON registro FOR EACH ROW BEGIN 
	DECLARE COD INT;
    SET COD = (SELECT IFNULL(MAX(CONVERT(SUBSTRING(ID_PACIENTE, 2,5), SIGNED INTEGER)), 0) FROM REGISTRO) + 1;
    SET NEW.ID_PACIENTE = CONCAT('P', LPAD(COD,5,'0'));
END
$$
DELIMITER ;


DELIMITER $$
CREATE TRIGGER tr_insertbasehisto AFTER INSERT ON contratos FOR EACH ROW BEGIN

  DECLARE _ID_PACIENTE VARCHAR(80);
  DECLARE _TIP_TRAB VARCHAR(80);
  DECLARE _SUB_TRAB VARCHAR(80);

  SET _ID_PACIENTE = NEW.ID_PACIENTE;
  SET _TIP_TRAB = NEW.TIP_TRAB;
  SET _SUB_TRAB = NEW.SUB_TRAB;

  INSERT INTO base_historial (ID_PACIENTE, TIP_TRAB, SUB_TRAB) VALUES (_ID_PACIENTE, _TIP_TRAB, _SUB_TRAB);

END
$$
DELIMITER ;


CREATE TABLE trabajo
(
  ID INT(11) PRIMARY KEY NOT NULL,
  ID_PACIENTE VARCHAR(10),
  TIP_TRAB varchar(200),
  SUB_TRAB varchar(200),
)


-- Crear la tabla 'cotizacion'
CREATE TABLE cotizacion (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_PACIENTE VARCHAR(10),
    FECHA DATE,
    MONTO DECIMAL(10, 2),
    OBSERVACION TEXT,
    SUB_TRAB VARCHAR(80),
    TIP_TRAB VARCHAR(80),
    PDF LONGBLOB
);

-- Crear la tabla 'lista_cotizacion'
CREATE TABLE lista_cotizacion (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_COTI INT,
    LISTA TEXT
);

-- Agregar la restricción de clave externa en 'lista_cotizacion'
ALTER TABLE lista_cotizacion
ADD CONSTRAINT fk_lista_cotizacion_cotizacion
FOREIGN KEY (ID_COTI) REFERENCES cotizacion(ID);



CREATE TABLE contratos( 
  ID INT PRIMARY KEY AUTO_INCREMENT,
  FECHA DATE,
  ID_PACIENTE VARCHAR(10),
  MONTO DECIMAL(10, 2),
  SUB_TRAB VARCHAR(80),
  TIP_TRAB VARCHAR(80),
  PDF LONGBLOB
);

CREATE TABLE pagoscontrato (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  ID_CONTRATO INT,
  ID_PACIENTE VARCHAR(10),
  FECHA DATE DEFAULT CURDATE(),
  NPAGO VARCHAR(20),
  ABONO DECIMAL(10,2),
  TIP_PAGO VARCHAR(50),
  METODO VARCHAR(100),
  COMPROBANTE LONGBLOB,
  PDF LONGBLOB
);

ALTER TABLE pagoscontrato
ADD CONSTRAINT fk_pagoscontrato_contratos
FOREIGN KEY (ID_CONTRATO) REFERENCES contratos(ID);
